### PR TITLE
subset Table objects

### PR DESCRIPTION
**Pull request by tiemvanderdeure**
This implements `getindex`, `view`, and `Tables.subset`, so it is possible to select a subset of rows of a `GBIF2.Table` and get a Table back. 

(I also fixed a little typo in the show method)

### CODE REVIEW

**Comment by tiemvanderdeure** [comment]
Documentation fails on `LoadError: ArgumentError: Package LibGit2 does not have LibGit2_jll in its dependencies`, which I've never seen before. I think it might have something to do with the change to julia v1.11?

**Comment by rafaqz** [comment]
Yeah looks like not our problem. But I thought it was fixed. Maybe we have some old deps?

**Comment by rafaqz** [comment]
Oh there is a Manifest.toml in the docs we need to delete

**Comment by tiemvanderdeure** [comment]
That worked!

**Pull request merged**
